#Testing webhook
# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton
  labels:
    app: tekton
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tekton
  template:
    metadata:
      labels:
        app: tekton
    spec:
      containers:
        - name: tekton
          image: tekton:latest
          ports:
            - containerPort: 80
          env:
            - name: PYTHONUNBUFFERED
              value: "1"

---
apiVersion: v1
kind: Service
metadata:
  name: tekton-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: tekton
