apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-pullrequest-listener
spec:
  serviceAccountName: tekton-triggers-github-sa
  triggers:
    - name: github-pullrequest-trigger
      interceptors:
        - ref:
            name: cel
          params:
            - name: filter
              value: "header.match('X-GitHub-Event', 'pull_request')"
        - ref:
            name: "github"
          params:
            - name: secretRef
              value:
                secretName: github-webhook-secret  
                secretKey: secret
            - name: "X-Hub-Signature-256"
            - name: algorithm
              value: sha256 
      bindings:
        - ref: github-payload-binding
      template:
        ref: github-pipeline-template
