apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: github-pipeline-template
spec:
  params:
    - name: action
    - name: pull_request_id
    - name: git-url
    - name: docker-image
    - name: branch    
    - name: sha    
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pullrequest-pipeline-run-
      spec:
        pipelineRef:
          name: testcase-pipeline
        params:
          - name: action
            value: "$(tt.params.action)"
          - name: pull_request_id
            value: "$(tt.params.pull_request_id)"
          - name: git-url
            value: "https://github.com/AmbeshGaunker/tekton-app"
          - name: docker-image
            value: "docker.io/ambesh123/tekton"
          - name: branch 
            value: "$(tt.params.branch)"
          - name: sha      
            value: "$(tt.params.sha)"
        workspaces:
          - name: myworkspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 50Mi
