apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce.
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: overlay
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: IMAGE_PUSH_SECRET_NAME
      description: Kubernetes secrets contain image push username and password
  workspaces:
    - name: source
  volumes:
    - name: varlibcontainers
      emptyDir: {}
    - name: build-cache
      emptyDir: {} 
  steps:
    - name: build
      image: quay.io/buildah/stable:v1
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          --no-cache \
          --build-arg BUILDAH_CACHE_PATH=/cache \
          -f $(params.DOCKERFILE) -t $(params.IMAGE) .
        if [ $? -eq 0 ]; then
          echo "Build succeeded" > $(results.status.path)
        else
          echo "Build failed" > $(results.status.path)
        fi
      volumeMounts:
        - name: varlibcontainers
          mountPath: /var/lib/containers
        - name: build-cache
          mountPath: /cache
      securityContext:
        privileged: true
  results:
    - name: status
      description: The result of the build
