apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: testcase-pipelinerun
spec:
  pipelineRef:
    name: testcase-pipeline
  params:
    - name: git-url
      value: https://github.com/AmbeshGaunker/tekton-app
    - name: docker-image
      value: docker.io/ambesh123/tekton
    - name: branch                
      value: "main"   
  workspaces:
    - name: myworkspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Mi
